#!/usr/bin/env bash

#nixos-rebuild switch -I nixos-config=$HOME/config/configuration.nix

# The #valorium specifies the system hostname to build for.
# This only important when building on a new blank system.
nixos-rebuild switch --flake "/home/naharie/config#valorium"