[
  ./boot-loader.nix
  ./chaotic-nix.nix
  ./desktop-environment-plasma.nix
  ./desktop-environment.nix
  ./environment-variables.nix
  ./graphics.nix
  ./hardware-configuration.nix
  ./hardware-corsair.nix
  ./home.nix
  ./localization.nix
  ./networking.nix
  ./nixpkgs.nix
  ./sound.nix
  ./programs
  ./services
  ./users
]